# URL de conexão apontando para o localhost na porta mapeada pelo Docker
spring.datasource.url=jdbc:mysql://localhost:3307/autoescola_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rootpassword

# Estratégia do JPA e logs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ativação do Flyway para rodar o script SQL de migração automaticamente
spring.flyway.enabled=true